export default [
  {
    id: 32,
    firstSeason: { id: 19931994 },
    fullName: 'Anaheim Ducks',
    lastSeason: null,
    teamCommonName: 'Ducks',
    teamPlaceName: 'Anaheim',
  },
  {
    id: 28,
    firstSeason: { id: 19791980 },
    fullName: 'Arizona Coyotes',
    lastSeason: null,
    teamCommonName: 'Coyotes',
    teamPlaceName: 'Arizona',
  },
  {
    id: 6,
    firstSeason: { id: 19241925 },
    fullName: 'Boston Bruins',
    lastSeason: null,
    teamCommonName: 'Bruins',
    teamPlaceName: 'Boston',
  },
  {
    id: 19,
    firstSeason: { id: 19701971 },
    fullName: 'Buffalo Sabres',
    lastSeason: null,
    teamCommonName: 'Sabres',
    teamPlaceName: 'Buffalo',
  },
  {
    id: 21,
    firstSeason: { id: 19721973 },
    fullName: 'Calgary Flames',
    lastSeason: null,
    teamCommonName: 'Flames',
    teamPlaceName: 'Calgary',
  },
  {
    id: 26,
    firstSeason: { id: 19791980 },
    fullName: 'Carolina Hurricanes',
    lastSeason: null,
    teamCommonName: 'Hurricanes',
    teamPlaceName: 'Carolina',
  },
  {
    id: 11,
    firstSeason: { id: 19261927 },
    fullName: 'Chicago Blackhawks',
    lastSeason: null,
    teamCommonName: 'Blackhawks',
    teamPlaceName: 'Chicago',
  },
  {
    id: 27,
    firstSeason: { id: 19791980 },
    fullName: 'Colorado Avalanche',
    lastSeason: null,
    teamCommonName: 'Avalanche',
    teamPlaceName: 'Colorado',
  },
  {
    id: 36,
    firstSeason: { id: 20002001 },
    fullName: 'Columbus Blue Jackets',
    lastSeason: null,
    teamCommonName: 'Blue Jackets',
    teamPlaceName: 'Columbus',
  },
  {
    id: 15,
    firstSeason: { id: 19671968 },
    fullName: 'Dallas Stars',
    lastSeason: null,
    teamCommonName: 'Stars',
    teamPlaceName: 'Dallas',
  },
  {
    id: 12,
    firstSeason: { id: 19261927 },
    fullName: 'Detroit Red Wings',
    lastSeason: null,
    teamCommonName: 'Red Wings',
    teamPlaceName: 'Detroit',
  },
  {
    id: 25,
    firstSeason: { id: 19791980 },
    fullName: 'Edmonton Oilers',
    lastSeason: null,
    teamCommonName: 'Oilers',
    teamPlaceName: 'Edmonton',
  },
  {
    id: 33,
    firstSeason: { id: 19931994 },
    fullName: 'Florida Panthers',
    lastSeason: null,
    teamCommonName: 'Panthers',
    teamPlaceName: 'Florida',
  },
  {
    id: 14,
    firstSeason: { id: 19671968 },
    fullName: 'Los Angeles Kings',
    lastSeason: null,
    teamCommonName: 'Kings',
    teamPlaceName: 'Los Angeles',
  },
  {
    id: 37,
    firstSeason: { id: 20002001 },
    fullName: 'Minnesota Wild',
    lastSeason: null,
    teamCommonName: 'Wild',
    teamPlaceName: 'Minnesota',
  },
  {
    id: 1,
    firstSeason: { id: 19171918 },
    fullName: 'Montréal Canadiens',
    lastSeason: null,
    teamCommonName: 'Canadiens',
    teamPlaceName: 'Montréal',
  },
  {
    id: 34,
    firstSeason: { id: 19981999 },
    fullName: 'Nashville Predators',
    lastSeason: null,
    teamCommonName: 'Predators',
    teamPlaceName: 'Nashville',
  },
  {
    id: 23,
    firstSeason: { id: 19741975 },
    fullName: 'New Jersey Devils',
    lastSeason: null,
    teamCommonName: 'Devils',
    teamPlaceName: 'New Jersey',
  },
  {
    id: 22,
    firstSeason: { id: 19721973 },
    fullName: 'New York Islanders',
    lastSeason: null,
    teamCommonName: 'Islanders',
    teamPlaceName: 'New York',
  },
  {
    id: 10,
    firstSeason: { id: 19261927 },
    fullName: 'New York Rangers',
    lastSeason: null,
    teamCommonName: 'Rangers',
    teamPlaceName: 'New York',
  },
  {
    id: 30,
    firstSeason: { id: 19921993 },
    fullName: 'Ottawa Senators',
    lastSeason: null,
    teamCommonName: 'Senators',
    teamPlaceName: 'Ottawa',
  },
  {
    id: 16,
    firstSeason: { id: 19671968 },
    fullName: 'Philadelphia Flyers',
    lastSeason: null,
    teamCommonName: 'Flyers',
    teamPlaceName: 'Philadelphia',
  },
  {
    id: 17,
    firstSeason: { id: 19671968 },
    fullName: 'Pittsburgh Penguins',
    lastSeason: null,
    teamCommonName: 'Penguins',
    teamPlaceName: 'Pittsburgh',
  },
  {
    id: 29,
    firstSeason: { id: 19911992 },
    fullName: 'San Jose Sharks',
    lastSeason: null,
    teamCommonName: 'Sharks',
    teamPlaceName: 'San Jose',
  },
  {
    id: 18,
    firstSeason: { id: 19671968 },
    fullName: 'St. Louis Blues',
    lastSeason: null,
    teamCommonName: 'Blues',
    teamPlaceName: 'St. Louis',
  },
  {
    id: 31,
    firstSeason: { id: 19921993 },
    fullName: 'Tampa Bay Lightning',
    lastSeason: null,
    teamCommonName: 'Lightning',
    teamPlaceName: 'Tampa Bay',
  },
  {
    id: 5,
    firstSeason: { id: 19171918 },
    fullName: 'Toronto Maple Leafs',
    lastSeason: null,
    teamCommonName: 'Maple Leafs',
    teamPlaceName: 'Toronto',
  },
  {
    id: 20,
    firstSeason: { id: 19701971 },
    fullName: 'Vancouver Canucks',
    lastSeason: null,
    teamCommonName: 'Canucks',
    teamPlaceName: 'Vancouver',
  },
  {
    id: 38,
    firstSeason: { id: 20172018 },
    fullName: 'Vegas Golden Knights',
    lastSeason: null,
    teamCommonName: 'Golden Knights',
    teamPlaceName: 'Vegas',
  },
  {
    id: 24,
    firstSeason: { id: 19741975 },
    fullName: 'Washington Capitals',
    lastSeason: null,
    teamCommonName: 'Capitals',
    teamPlaceName: 'Washington',
  },
  {
    id: 35,
    firstSeason: { id: 19992000 },
    fullName: 'Winnipeg Jets',
    lastSeason: null,
    teamCommonName: 'Jets',
    teamPlaceName: 'Winnipeg',
  },
  {
    id: 8,
    firstSeason: { id: 19251926 },
    fullName: 'Brooklyn Americans',
    lastSeason: { id: 19411942 },
    teamCommonName: 'Americans',
    teamPlaceName: 'Brooklyn',
  },
  {
    id: 13,
    firstSeason: { id: 19671968 },
    fullName: 'Cleveland Barons',
    lastSeason: { id: 19771978 },
    teamCommonName: 'Barons',
    teamPlaceName: 'Cleveland',
  },
  {
    id: 4,
    firstSeason: { id: 19191920 },
    fullName: 'Hamilton Tigers',
    lastSeason: { id: 19241925 },
    teamCommonName: 'Tigers',
    teamPlaceName: 'Hamilton',
  },
  {
    id: 7,
    firstSeason: { id: 19241925 },
    fullName: 'Montreal Maroons',
    lastSeason: { id: 19371938 },
    teamCommonName: 'Maroons',
    teamPlaceName: 'Montreal',
  },
  {
    id: 2,
    firstSeason: { id: 19171918 },
    fullName: 'Montreal Wanderers',
    lastSeason: { id: 19171918 },
    teamCommonName: 'Wanderers',
    teamPlaceName: 'Montreal',
  },
  {
    id: 9,
    firstSeason: { id: 19251926 },
    fullName: 'Philadelphia Quakers',
    lastSeason: { id: 19301931 },
    teamCommonName: 'Quakers',
    teamPlaceName: 'Philadelphia',
  },
  {
    id: 3,
    firstSeason: { id: 19171918 },
    fullName: 'St. Louis Eagles',
    lastSeason: { id: 19341935 },
    teamCommonName: 'Eagles',
    teamPlaceName: 'St. Louis',
  },
]
